# -*- coding: utf-8 -*-
"""Primeiros passos Google Colab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/cavalcantetreinamentos/curso_python/blob/master/Primeiros_passos_Google_Colab.ipynb

# Aprendendo Google Colab - Cavalcante Treinamentos
---

# Executar código é muito simples
Use  **CTRL + ENTER** - Executa o código

ou  **SHIFT + ENTER** - Executa o código e pula para a próxima célula

ou  **ALT + ENTER** - Executa o código e cria uma nova célula
"""

print('Olá seja bem vindo!!')

"""# Entrada de Dados"""

nome = input('Qual é seu nome: ')
print(nome + ' seja bem vindo ao curso de Python')

"""# Executar comandos Linux"""

!cat /proc/cpuinfo
!cat /proc/meminfo

"""# Instalar biblioteca"""

!pip install requests

!pip install tensorflow==1.2

"""# Saída de dados ricas"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Fills and Alpha Example")
plt.show()

"""# Utilizando a ajuda integrada
1. Use a tecla tab para executar o Intelisense
2. No final de um comando/função ou método adicione uma ?. E execute a célula  **SHIFT + ENTER**.
"""

import numpy as np
np.random?

"""# Parar execução de um código mal comportado
>**CTRL+M I**
"""

while(True):
  pass

"""# Integração Drive e GitHub
---
>## Permite abrir e salvar arquivos nessas aplicações

# Trabalhando de forma colaborativa
1. Compartilhando seu código
2. Adicionando e resolvendo comentários
"""

texto = 'Claudio'

"""# Executando o código em uma GPU ou TPU
>Clicar em Edit > Noteboolk Settings

# Adicionando fórmulas matemáticas para enriquecer seu texto

$\frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$


$x^2 + 2xy + y^2 $

$\sqrt{3x-1}+(1+x)^2$

# Adicionando Imagens e Links
Fazer um link é bem simples como isso [Aprenda Python](https://www.youtube.com/watch?v=4ltJ5jDsxu8&list=PLQ7gVTPc8KmiIpPLxN30N0GJ6zpMcXDNL)

Adicionar imagem faz dessa maneira:
 ![Python é simplesmente sensacional](https://semantix.com.br/wp-content/uploads/2019/09/dlanor-s-2xEQDxB0ss4-unsplash.jpg)

#Trocar o tema

***Se você gosta  de um tema mais dark é fácil trocar.***
>>Tools => Settings
"""

